# Generated by Django 4.1.4 on 2022-12-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student", name="borrow", field=models.IntegerField(default=0),
        ),
    ]
